# Generated by Django 3.1 on 2022-04-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('comp_logo', models.FileField(upload_to='uploads')),
                ('work_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('mainImg', models.FileField(upload_to='uploads')),
                ('img1', models.FileField(upload_to='uploads')),
                ('img2', models.FileField(upload_to='uploads')),
                ('img3', models.FileField(upload_to='uploads')),
                ('img4', models.FileField(upload_to='uploads')),
                ('desc', models.CharField(max_length=200)),
                ('live_link', models.CharField(max_length=200)),
                ('github_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
