# Generated by Django 3.1 on 2022-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='work_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
