# Generated by Django 3.1 on 2022-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20220409_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='comp_logo',
        ),
        migrations.AddField(
            model_name='experience',
            name='comp_pos',
            field=models.TextField(null=True),
        ),
    ]
